name: Keep Streamlit Alive

on:
  schedule:
    # Uruchamia się co 6 godzin (0:00, 6:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  # Pozwala na ręczne uruchomienie akcji z poziomu zakłądki Actions na GitHubie
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request to Streamlit app
        run: |
          curl -s -L --max-time 30 "https://farad-bot.streamlit.app/" > /dev/null && echo "App pinged successfully!"